### PR TITLE
More features and updates

### LINKED ISSUE #14: Show QR code in Receive
Currently, only a placeholder is shown.
Also, the copy button does not work.

### LINKED ISSUE #15: Dashboard: add link from active extensions pill to Wallet settings
Make the link of active extensions (green) clickable and navigate to wallet settings (where user can add more extensions)

### PR DESCRIPTION
**Pull request by friedger**
This PR
* fixes the use of demo mode,
* introduces RedButton and CSWCard
* adds a price service object
* improves responsive design
* fixes #14 
* fixes #15

### CODE REVIEW

File: ui-v3/src/hooks/useSelectedWallet.ts [hunk 1]
```diff
@@ -17,47 +18,50 @@ interface SelectedWallet {
...
+          contractId: "SP2J6ZY48GV1EZ5V2V5RB9MP66SW86PYKKNRV9EJ7.demo-smart-wallet",
+          balance: "10,000.00 STX",
+          usdValue: "$20,000.00",
+          address: "SP2J6ZY48GV1EZ5V2V5RB9MP66SW86PYKKNRV9EJ7",
+          extensions: ["Multi-sig", "Time-lock", "Treasury", "Stacking"]
+        };
+        setSelectedWallet(demoWallet);
+      } else if (walletId) {
+        // Check if this is an imported wallet by looking for imported wallet indicators
+        const isImportedWallet = walletId.includes('.') && walletId.length > 20;
```
Comment (friedger) [inline ui-v3/src/hooks/useSelectedWallet.ts:40]: This is wrong and should be fixed in a separate PR

Comment (Zeus-Adin) [reply ui-v3/src/hooks/useSelectedWallet.ts:40]: yes done
